# Generated by Django 4.1.7 on 2024-02-02 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0004_alter_clasemiembro_hexcolor_alter_miembro_clase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=25)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=25)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=30)),
                ('fecha_pago', models.DateField()),
                ('proveedor', models.CharField(max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='club.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=8)),
                ('fecha_pago', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='club.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('importe', models.FloatField()),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cuentacontable')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.salida')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.FloatField()),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.concepto')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cuentacontable')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.entrada')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='club.miembro')),
            ],
        ),
    ]
