# Generated by Django 4.1.7 on 2024-01-29 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Clase de miembro',
                'verbose_name_plural': 'Clases de miembros',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de miembro',
                'verbose_name_plural': 'Tipos de miembros',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('miembro_iglesia', models.BooleanField(default=True, verbose_name='¿Es miembro de la IASD?')),
                ('clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='club.clasemiembro')),
                ('tipo_miembro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='club.tipomiembro')),
            ],
            options={
                'verbose_name': 'miembro',
                'verbose_name_plural': 'miembros',
                'ordering': ['nombre', 'clase'],
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_familia', models.CharField(max_length=200)),
                ('miembro', models.ManyToManyField(blank=True, to='club.miembro')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
                'ordering': ['nombre_familia', 'miembro__nombre'],
            },
        ),
    ]
