# Generated by Django 4.1.7 on 2024-01-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familia',
            options={'ordering': ['nombre_familia'], 'verbose_name': 'Familia', 'verbose_name_plural': 'Familias'},
        ),
    ]
