# Generated by Django 4.1.7 on 2024-01-29 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_familia_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='miembro',
        ),
        migrations.AddField(
            model_name='clasemiembro',
            name='hexcolor',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='miembro',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.familia'),
        ),
    ]
