# Generated by Django 4.1.7 on 2024-01-29 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_remove_familia_miembro_clasemiembro_hexcolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasemiembro',
            name='hexcolor',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='clase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='club.clasemiembro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='miembro',
            name='tipo_miembro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='club.tipomiembro'),
            preserve_default=False,
        ),
    ]
